services:
  postgres:
    image: postgres:16
    container_name: fb_postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-facebook_clone}
      POSTGRES_USER: ${POSTGRES_USER:-fb_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fb_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-fb_admin} -d ${POSTGRES_DB:-facebook_clone}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: fb_redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: mcr.microsoft.com/dotnet/sdk:10.0
    container_name: fb_api_dev
    profiles: ["dev-api"]
    working_dir: /workspace/backend
    command:
      - dotnet
      - watch
      - --project
      - src/FacebookClone.API/FacebookClone.API.csproj
      - run
      - --no-launch-profile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: "5286"
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
      DOTNET_WATCH_SUPPRESS_LAUNCH_BROWSER: "1"
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=${POSTGRES_DB:-facebook_clone};Username=${POSTGRES_USER:-fb_admin};Password=${POSTGRES_PASSWORD:-fb_password};GSS Encryption Mode=Disable
      Redis__ConnectionString: redis:6379
      Database__AutoMigrate: ${Database__AutoMigrate:-true}
      Database__AutoSeed: ${Database__AutoSeed:-true}
      Jwt__Secret: ${Jwt__Secret:-THIS_IS_A_SUPER_SECRET_KEY_CHANGE_LATER}
      Jwt__Issuer: ${Jwt__Issuer:-FacebookClone}
      Jwt__Audience: ${Jwt__Audience:-FacebookCloneClient}
      Jwt__AccessTokenMinutes: ${Jwt__AccessTokenMinutes:-15}
      Jwt__RefreshTokenDays: ${Jwt__RefreshTokenDays:-7}
    ports:
      - "5286:5286"
    volumes:
      - ./backend:/workspace/backend
      - dotnet_nuget:/root/.nuget/packages
      - dotnet_dataprotection:/root/.aspnet/DataProtection-Keys
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pg_data:
  redis_data:
  dotnet_nuget:
  dotnet_dataprotection:
