#!/usr/bin/env python3
"""Generate FE (JS) and BE (C#) source from shared/contracts/*.json.

Usage:
    python scripts/generate_shared_contracts.py          # write generated files
    python scripts/generate_shared_contracts.py --check  # fail if out of date (CI)

Runs on both `python` and `python3`. No third-party deps.
"""
from __future__ import annotations
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTRACTS = ROOT / "shared" / "contracts"
CS_ENUMS_DIR = ROOT / "backend" / "src" / "FacebookClone.Domain" / "Enums" / "Generated"
CS_CONSTANTS_DIR = ROOT / "backend" / "src" / "FacebookClone.Domain" / "Constants" / "Generated"
JS_DIR = ROOT / "frontend" / "Facebook_Frontend" / "src" / "shared" / "generated"

AUTOGEN = "// <auto-generated> Generated from shared/contracts. DO NOT EDIT. Run scripts/generate_shared_contracts.py."


def load(name: str) -> dict:
    return json.loads((CONTRACTS / name).read_text(encoding="utf-8"))


def gen_csharp_enums(enums: dict, ns: str) -> str:
    out = [AUTOGEN, "", f"namespace {ns};", ""]
    for enum_name, members in enums.items():
        out.append(f"public enum {enum_name}")
        out.append("{")
        items = list(members.items())
        for i, (k, v) in enumerate(items):
            comma = "," if i < len(items) - 1 else ""
            out.append(f"    {k} = {v}{comma}")
        out.append("}")
        out.append("")
    return "\n".join(out) + "\n"


def gen_csharp_string_consts(groups: dict, ns: str) -> str:
    out = [AUTOGEN, "", f"namespace {ns};", ""]
    for cls, members in groups.items():
        out.append(f"public static class {cls}")
        out.append("{")
        for k, v in members.items():
            out.append(f'    public const string {k} = "{v}";')
        out.append("}")
        out.append("")
    return "\n".join(out) + "\n"


def gen_js_enums(enums: dict, string_consts: dict) -> str:
    out = [AUTOGEN.replace("//", "//"), ""]
    for enum_name, members in enums.items():
        pairs = ", ".join(f"{k}: {v}" for k, v in members.items())
        out.append(f"export const {enum_name} = Object.freeze({{ {pairs} }});")
    out.append("")
    for cls, members in string_consts.items():
        pairs = ", ".join(f'{k}: "{v}"' for k, v in members.items())
        out.append(f"export const {cls} = Object.freeze({{ {pairs} }});")
    out.append("")
    return "\n".join(out) + "\n"


def gen_js_constants(c: dict) -> str:
    out = [AUTOGEN, ""]

    def emit(name: str, obj: dict):
        pairs = ", ".join(
            f'{k}: {json.dumps(v)}' for k, v in obj.items()
        )
        out.append(f"export const {name} = Object.freeze({{ {pairs} }});")

    emit("API", c["api"])
    emit("HUBS", c["hubs"])
    emit("STORAGE_KEYS", c["storageKeys"])
    emit("LIMITS", c["limits"])
    emit("TIMERS", c["timers"])
    emit("LIVE", c["live"])
    emit("LOCALIZATION", c["localization"])
    emit("SECURITY", c["security"])
    emit("OFFLINE", c["offline"])
    emit("UPLOAD_CHUNKS", c["uploadChunks"])
    out.append("")
    return "\n".join(out) + "\n"


def gen_js_localization_catalog(catalog: dict) -> str:
    payload = json.dumps(catalog, ensure_ascii=False, indent=2)
    return f"{AUTOGEN}\n\nexport const LOCALIZATION_CATALOG = Object.freeze({payload});\n"


def gen_csharp_localization_catalog(catalog: dict) -> str:
    def literal(value: str) -> str:
        return json.dumps(value, ensure_ascii=False)

    source_locale = catalog["sourceLocale"]
    rows: list[tuple[str, str, str, str, str]] = []
    for entry in catalog["entries"]:
        rows.append((
            entry["key"],
            source_locale,
            entry["sourceText"],
            entry["sourceText"],
            entry.get("context", ""),
        ))
        for target_locale, value in entry.get("translations", {}).items():
            rows.append((
                entry["key"],
                target_locale,
                entry["sourceText"],
                value,
                entry.get("context", ""),
            ))

    out = [
        AUTOGEN,
        "",
        "namespace FacebookClone.Domain.Constants;",
        "",
        "public sealed record LocalizationCatalogItem(",
        "    string Key,",
        "    string TargetLocale,",
        "    string SourceText,",
        "    string Value,",
        "    string Context);",
        "",
        "public static class LocalizationCatalog",
        "{",
        f"    public const string SourceLocale = {literal(source_locale)};",
        "",
        "    public static readonly IReadOnlyList<LocalizationCatalogItem> Entries =",
        "    [",
    ]
    for key, target_locale, source_text, value, context in rows:
        out.append(
            "        new("
            f"{literal(key)}, {literal(target_locale)}, {literal(source_text)}, "
            f"{literal(value)}, {literal(context)}),"
        )
    out.extend(["    ];", "}"])
    return "\n".join(out) + "\n"


def pascal(name: str) -> str:
    parts: list[str] = []
    current = ""
    for ch in name:
        if ch in "_- ":
            if current:
                parts.append(current)
                current = ""
        elif ch.isupper() and current:
            parts.append(current)
            current = ch
        else:
            current += ch
    if current:
        parts.append(current)
    return "".join(part[:1].upper() + part[1:] for part in parts)


def csharp_literal(value):
    if isinstance(value, bool):
        return "true" if value else "false", "bool"
    if isinstance(value, int):
        return str(value), "int"
    if isinstance(value, float):
        return f"{value}", "double"
    return json.dumps(str(value)), "string"


def csharp_member(name: str, value) -> str:
    if isinstance(value, list):
        if all(isinstance(item, int) for item in value):
            items = ", ".join(str(item) for item in value)
            return f"        public static readonly IReadOnlyList<int> {name} = [{items}];"

        items = ", ".join(json.dumps(str(item)) for item in value)
        return f"        public static readonly IReadOnlyList<string> {name} = [{items}];"

    literal, value_type = csharp_literal(value)
    return f"        public const {value_type} {name} = {literal};"


def gen_csharp_constants(c: dict) -> str:
    groups = {
        "Api": c["api"],
        "Hubs": c["hubs"],
        "StorageKeys": c["storageKeys"],
        "Limits": c["limits"],
        "Timers": c["timers"],
        "Live": c["live"],
        "Localization": c["localization"],
        "Security": c["security"],
        "Offline": c["offline"],
        "UploadChunks": c["uploadChunks"],
    }

    out = [AUTOGEN, "", "namespace FacebookClone.Domain.Constants;", "", "public static class SharedConstants", "{"]
    for group_name, values in groups.items():
        out.append(f"    public static class {group_name}")
        out.append("    {")
        for key, value in values.items():
            out.append(csharp_member(pascal(key), value))
        out.append("    }")
        out.append("")
    out.append("}")
    return "\n".join(out) + "\n"


def write_or_check(path: Path, content: str, check: bool, stale: list):
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    # normalize line endings for comparison
    if existing is not None and existing.replace("\r\n", "\n") == content.replace("\r\n", "\n"):
        return
    if check:
        stale.append(str(path.relative_to(ROOT)))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"  wrote {path.relative_to(ROOT)}")


def main() -> int:
    check = "--check" in sys.argv
    enums_doc = load("enums.json")
    constants_doc = load("constants.json")
    localization_catalog = load("localization-catalog.json")
    ns = enums_doc.get("csharpNamespace", "FacebookClone.Domain.Enums")
    enums = enums_doc["enums"]
    string_consts = enums_doc.get("stringConstants", {})

    stale: list[str] = []
    print("Generating shared contracts..." if not check else "Checking shared contracts...")

    write_or_check(CS_ENUMS_DIR / "Enums.g.cs", gen_csharp_enums(enums, ns), check, stale)
    write_or_check(CS_ENUMS_DIR / "StringConstants.g.cs", gen_csharp_string_consts(string_consts, ns), check, stale)
    write_or_check(CS_CONSTANTS_DIR / "Constants.g.cs", gen_csharp_constants(constants_doc), check, stale)
    write_or_check(CS_CONSTANTS_DIR / "LocalizationCatalog.g.cs", gen_csharp_localization_catalog(localization_catalog), check, stale)
    write_or_check(JS_DIR / "enums.js", gen_js_enums(enums, string_consts), check, stale)
    write_or_check(JS_DIR / "constants.js", gen_js_constants(constants_doc), check, stale)
    write_or_check(JS_DIR / "localizationCatalog.js", gen_js_localization_catalog(localization_catalog), check, stale)

    if check and stale:
        print("ERROR: generated files are out of date with shared/contracts:")
        for s in stale:
            print(f"  - {s}")
        print("Run: python scripts/generate_shared_contracts.py")
        return 1
    print("Done." if not check else "Up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
